# Which RPC node to use.
rpc_url: https://eth-mainnet.public.blastapi.io

# The reference currency for prices, usually makes the most sense in USDC/USDT.
base:
  erc20:
    symbol: USDC
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    decimals: 6

  # erc20:
  #   symbol: WBTC
  #   address: "2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
  #   decimals: 8

# The comparison currency. Prices will be in "base" units to 1 "quote" unit.
quote:
  native:

# The strategy to execute.
strategy:
  # Do nothing.
  empty:

  # Always buy the provided amount.
  # always_buy: 1

  # Always sell the provided amount.
  # always_sell: 1

  # Buy if beelow the below threshold, sell if above the sell threshold. Each of buy/sell are optional.
  # threshold:
  #   buy:
  #     at: 2060
  #     amount:
  #       numerator: 1
  #       denominator: 10
  #   sell:
  #     at: 2070
  #     amount:
  #       numerator: 1
  #       denominator: 10

  # Provide an exponential moving average of the price to the inner strategy.
  # ema:
  #   carry: 0.95
  #   inner:
  #     threshold:
  #       buy:
  #         at: 2030
  #         amount: 2
  #       sell:
  #         at: 2090
  #         amount: 2
