chain_id: 1
rpc_url: https://eth-mainnet.public.blastapi.io

base:
  erc20:
    symbol: USDC
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
    decimals: 2
  # erc20:
  #   symbol: WBTC
  #   address: "2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599"
  #   decimals: 8

quote:
  native:

strategy:
  threshold:
    buy:
      at: 2060
      amount:
        numerator: 1
        denominator: 10
    sell:
      at: 2070
      amount:
        numerator: 1
        denominator: 10
